services:
  # The Database Service for storing persistent data
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=kudospoints_user
      - POSTGRES_PASSWORD=kudospoints_password
      - POSTGRES_DB=kudospoints_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # The Message Broker for asynchronous communication
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    # Note: Uses default guest/guest credentials for local development set by the maintainers as default in the image
    ports:
      - "5672:5672"   # Port for AMQP protocol (application connections)
      - "15672:15672" # Port for the web-based management UI
    # We shall use "Anonymous volume" as losing messages on a local dev restart isn't critical

  # The Core Points Service Application
  app:
    build: . # tells compose to look for Dockerfile and build an image from it.
    container_name: points-bank
    ports:
      - "8080:8080"
    environment:
      # overrides datasource URL in app.props to connect to postgres service on Docker network
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kudospoints_db
    depends_on:
      - postgres

volumes:
  # "Named volume" to persist postgres database data
  postgres-data: {}
