services:
  # The Database Service
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=kudospoints_user
      - POSTGRES_PASSWORD=kudospoints_password
      - POSTGRES_DB=kudospoints_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # The Application Service
  app:
    build: . # tells compose to look for Dockerfile and build an image from it.
    container_name: points-bank
    ports:
      - "8080:8080"
    environment:
      # overrides props in app.props
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kudospoints_db
    depends_on:
      - postgres

volumes:
  postgres-data: {}